# Configuration for nextcloud setup

# Name of the lukasz-nextcloud application
name: lukaszcloud

# Service definitions for the lukasz-nextcloud application
services:
  # Service name: app
  # The `app` service definition
  lukasz-nextcloud:
    # Define the container name
    container_name: lukasz-nextcloud
    # Use the nextcloud image from the official Docker Hub
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.10
    # Restart the container unless stopped
    restart: unless-stopped
    # Map port 7580 on the host to port 80 on the container
    ports:
      - 7580:80
    # Mount the /DATA/AppData/$AppID/html directory on the host to /var/www/html in the container
    volumes:
      - /DATA/AppData/$AppID/html:/var/www/html
    # Set environment variables for the container
    environment:
      - POSTGRES_HOST=lukasz-pgbouncer
      - REDIS_HOST=lukasz-redis-nextcloud
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=casaos
      - NEXTCLOUD_ADMIN_PASSWORD=casaos
      - TRUSTED_PROXIES=
      - OVERWRITEPROTOCOL=http
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=4096M
      - OVERWRITECLIURL=https://example.com
      - OVERWRITEHOST=example.com
    # Specify the dependencies
    depends_on:
      lukasz-db-nextcloud:
        condition: service_healthy
      lukasz-redis-nextcloud:
        condition: service_healthy

    # Define the network
    networks:
      - lukasz_nextcloud_network

    x-casaos: # CasaOS specific configuration
      volumes:
        - container: /var/www/html
          description:
            en_us: "Container Path: /var/www/html"
      envs:
        - container: POSTGRES_HOST
          description:
            en_us: Database host
        - container: REDIS_HOST
          description:
            en_us: Redis host
        - container: POSTGRES_PASSWORD
          description:
            en_us: Database password
        - container: POSTGRES_USER
          description:
            en_us: Database user
        - container: POSTGRES_DB
          description:
            en_us: Database type
        - container: NEXTCLOUD_ADMIN_USER
          description:
            en_us: Nextcloud admin user
        - container: NEXTCLOUD_ADMIN_PASSWORD
          description:
            en_us: Nextcloud admin password
        - container: TRUSTED_PROXIES
          description:
            en_us: Trusted proxies
        - container: OVERWRITEPROTOCOL
          description:
            en_us: Overwrite protocol
        - container: OVERWRITECLIURL
          description:
            en_us: Overwrite CLI URL
        - container: OVERWRITEHOST
          description:
            en_us: Overwrite host
        - container: PHP_UPLOAD_LIMIT
          description:
            en_us: PHP upload limit
      ports:
        - container: "7580"
          description:
            en_us: "Container Port: 7580"

  # Define the database container for Nextcloud
  lukasz-db-nextcloud:
    container_name: lukasz-db-nextcloud
    image: postgres:14.2
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data # Mount the PostgreSQL data directory
    environment:
      - POSTGRES_PASSWORD=casaos # Set the PostgreSQL password
      - POSTGRES_USER=casaos # Set the PostgreSQL username
      - POSTGRES_DB=nextcloud # Set the name of the Nextcloud database
    networks:
      - lukasz_nextcloud_network # Connect to the Nextcloud network

    # Healthcheck configuration for the database service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casaos -d nextcloud"]
      interval: 10s
      timeout: 5s
      retries: 5

    x-casaos:
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: Database password
        - container: POSTGRES_USER
          description:
            en_us: Database user
        - container: POSTGRES_DB
          description:
            en_us: Database type

  lukasz-pgbouncer:
    container_name: lukasz-pgbouncer
    image: edoburu/pgbouncer
    restart: unless-stopped
    environment:
      - DB_USER=casaos
      - DB_PASSWORD=casaos
      - DB_HOST=lukasz-db-nextcloud
      - DB_NAME=nextcloud
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=200
      - DEFAULT_POOL_SIZE=20
      - RESERVE_POOL_SIZE=5
      - RESERVE_POOL_TIMEOUT=3
      - SERVER_RESET_QUERY=DISCARD ALL
    ports:
      - 6432:5432
    networks:
      - lukasz_nextcloud_network
    x-casaos:
      envs:
        - container: DB_USER
          description:
            en_us: Database user for PgBouncer (should match Nextcloud user)
        - container: DB_PASSWORD
          description:
            en_us: Password for the database user
        - container: DB_HOST
          description:
            en_us: Hostname or address of the PostgreSQL server
        - container: DB_NAME
          description:
            en_us: Database name to connect to
        - container: POOL_MODE
          description:
            en_us: Pooling mode (usually 'transaction' for Nextcloud)
        - container: MAX_CLIENT_CONN
          description:
            en_us: Maximum client connections PgBouncer will accept
        - container: DEFAULT_POOL_SIZE
          description:
            en_us: Number of server connections to keep in the pool per db/user
        - container: RESERVE_POOL_SIZE
          description:
            en_us: Additional connections in reserve pool
        - container: RESERVE_POOL_TIMEOUT
          description:
            en_us: Seconds a client waits for a connection from reserve pool
        - container: SERVER_RESET_QUERY
          description:
            en_us: Query to reset server connection before reuse

  # Redis configuration for Nextcloud

  lukasz-redis-nextcloud:
    container_name: lukasz-redis-nextcloud
    user: "1000:1000"
    image: redis:6.2.6
    restart: unless-stopped
    volumes:
      - "/DATA/AppData/$AppID/redis:/data" # Mount the Redis data directory
    networks:
      - lukasz_nextcloud_network # Connect to the Nextcloud network

    # Healthcheck configuration for the Redis service
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: "Container Path: /data"
      ports:
        - container: "6379"
          description:
            en_us: "Container Port: 6379"

  lukasz-cron:
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.10
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/html:/var/www/html
    entrypoint: /cron.sh
    # Specify the dependencies
    depends_on:
      db-nextcloud:
        condition: service_healthy
      redis-nextcloud:
        condition: service_healthy
    networks:
      - nextcloud_network # Connect to the Nextcloud network

    x-casaos:
      volumes:
        - container: /var/www/html
          description:
            en_us: "Container Path: /var/www/html"

# Network definition for the lukasz-nextcloud application
networks:
  lukasz_nextcloud_network:
    driver: bridge

# CasaOS specific configuration
x-casaos:
  # Supported CPU architectures for the application
  architectures:
    - amd64
    - arm64
  # Main service of the application
  main: nextcloud
  description:
    # Description in English
    en_us: Nextcloud puts your data at your fingertips, under your control. Store your documents, calendar, contacts and photos on a server at home, at one of our providers or in a data center you trust.
  tagline:
    en_us: The productivity platform that keeps you in control
  # Developer's name or identifier
  developer: "nextcloud"
  # Author of this configuration
  author: Lukasz
  # Icon for the application
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nextcloud.png
  # Thumbnail image (currently empty)
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/thumbnail.jpg
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-3.png
  title:
    # Title in English
    en_us: Nextcloud
  # Application category
  category: Lukasz
  # Port mapping information
  port_map: "7580"
  tips:
    before_install:
      en_us: |
        Read the [Nextcloud installation guide](https://community.bigbeartechworld.com/t/added-nextcloud-to-bigbearcasaos/455?u=dragonfire1119)
